# Auto-generated by .github/workflows/release.yml on each tag push.
# Until the first YYYY.M.D tag is pushed, the URLs below resolve to nothing
# and `brew install` will fail. Push a tag to publish a working formula.
class Cic < Formula
  desc "Terminal UI for monitoring CI builds across GitHub Actions and Jenkins"
  homepage "https://github.com/grahambrooks/cic"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/cic/releases/download/#{version}/cic-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/grahambrooks/cic/releases/download/#{version}/cic-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/grahambrooks/cic/releases/download/#{version}/cic-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "cic"
  end

  test do
    assert_match "Terminal UI", shell_output("#{bin}/cic --help")
  end
end
