# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Cic < Formula
  desc "Terminal UI for monitoring CI builds across GitHub Actions and Jenkins"
  homepage "https://github.com/grahambrooks/cic"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/cic/releases/download/v2026.10.1/cic-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "7b2804e5c99f67ad7f827bd2b2f07f1aec7db53d5c2259ae7e2852c59b241c98"
    end
    on_intel do
      url "https://github.com/grahambrooks/cic/releases/download/v2026.10.1/cic-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "1d1c2144fccb116f0d244004dc1446464390bdfc7a17d64bbf711ebac94f651e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/cic/releases/download/v2026.10.1/cic-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f3840fbb263093f8531099d17f75bc7e731ed9fb5e20607b9f2ef07e032a5968"
    end
    on_intel do
      url "https://github.com/grahambrooks/cic/releases/download/v2026.10.1/cic-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9aa617604c3f0daccbd9df82b428975df4b53a7b1bfd698ea7c49c0ae79fc5ed"
    end
  end

  def install
    bin.install "cic"
  end

  test do
    assert_path_exists bin/"cic"
  end
end
