# Generated by scripts/release.py (release-kit) from the v2026.9.0 release — do not edit.
class Cic < Formula
  desc "Terminal UI for monitoring CI builds across GitHub Actions and Jenkins"
  homepage "https://github.com/grahambrooks/cic"
  version "2026.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/cic/releases/download/v2026.9.0/cic-v2026.9.0-aarch64-apple-darwin.tar.gz"
      sha256 "c854babf2e52068761d8fdd30faa42419dd098b70fa19180ba1cfba10daa30d2"
    end
    on_intel do
      url "https://github.com/grahambrooks/cic/releases/download/v2026.9.0/cic-v2026.9.0-x86_64-apple-darwin.tar.gz"
      sha256 "27f042a44a86ceaae8f587e643f0a919c8dcf06f8a46d212575b59200a1e43e4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/cic/releases/download/v2026.9.0/cic-v2026.9.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "79d72c4978af87af42c667de7cee53fbea6f063d53c8e1548518aa8f4e1c186c"
    end
    on_intel do
      url "https://github.com/grahambrooks/cic/releases/download/v2026.9.0/cic-v2026.9.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0bc05bcb81f3447f8bbe6837c81a4826a1e1604a914688e4516f333723f81665"
    end
  end

  def install
    bin.install "cic"
  end

  test do
    assert_path_exists bin/"cic"
  end
end
